{% set name = "twilio" %}
{% set version = "6.57.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3a9a0e3882897185bf3a997408a43662bcfdec84250a701d06aff5b89bbaa9a1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - pyjwt ==1.7.1
    - python >=2.7
    - pytz
    - requests >=2.0.0
    - six

test:
  requires:
    - pip
  imports:
    - twilio
    - twilio.base
    - twilio.http
    - twilio.jwt
    - twilio.rest
    - twilio.twiml
  commands:
    - pip check

about:
  home: https://github.com/twilio/twilio-python/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Twilio API client and TwiML generator

extra:
  recipe-maintainers:
    - setu4993
