{% set name = "twilio" %}
{% set version = "6.47.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: effb4d6e9e9a9069065fbe21dea844597376ae6d6333626f14b05ba6b35bbb22

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - pyjwt >=1.4.2
    - python
    - pytz
    - requests >=2.0.0
    - six

test:
  imports:
    - twilio
    - twilio.base
    - twilio.http
    - twilio.jwt
    - twilio.rest
    - twilio.twiml

about:
  home: https://github.com/twilio/twilio-python/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Twilio API client and TwiML generator

extra:
  recipe-maintainers:
    - setu4993
